[[redirects]]
  from = "/"
  to = "/1.0"
  status = 301
  force = false

[[redirects]]
  from = "/0.1/*"
  to = "/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/1.0/fields-reference"
  to = "/1.0/field-options"
  status = 301
  force = false
