[[redirects]]
  from = "/"
  to = "/2.0"
  status = 301
  force = false

[[redirects]]
  from = "/0.1/*"
  to = "/0.4.x/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/1.0/fields-reference.html"
  to = "/1.0/field-options.html"
  status = 301
  force = false
